# Generated by Django 2.2.1 on 2019-05-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_in_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_job', to='helper.Users')),
                ('users_in_jobs', models.ManyToManyField(related_name='users_in_jobs', to='helper.Users')),
            ],
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
