# Generated by Django 2.2.1 on 2019-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_jobs_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
