# Generated by Django 2.2.1 on 2019-05-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_auto_20190528_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='assigned_to',
            field=models.IntegerField(),
        ),
    ]
