# Generated by Django 2.2.1 on 2019-05-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20190528_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='assigned_to',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories_in_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_in_job', to='helper.Jobs')),
            ],
        ),
    ]
